[build]
  publish = "/"  # Publish your root directory if there's no build process
  functions = "netlify/functions"  # The directory where your Netlify functions are

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301
  force = true
